package com.nanjiqie.mall.mapper;

import com.nanjiqie.mall.pojo.Seller;
import com.nanjiqie.mall.pojo.SellerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int countByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int deleteByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int insertSelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    List<Seller> selectByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    Seller selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int updateByExample(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int updateByPrimaryKeySelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated Fri Sep 23 11:22:20 CST 2022
     */
    int updateByPrimaryKey(Seller record);
}